services:
  - type: web
    name: agromercado-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0